name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up NodeJS
    - name: Set up NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    # Install NodeJS dependencies
    - name: Install NodeJS dependencies
      run: npm install

    # SonarQube Scan
    - name: SonarQube Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
        unzip sonar-scanner.zip
        export PATH="$PWD/sonar-scanner-5.0.1.3006-linux/bin:$PATH"
        sonar-scanner \
          -Dsonar.projectKey=my-project \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarqube.satyaji.shop \
          -Dsonar.login=$SONAR_TOKEN

    # Set up Java and Maven
    - name: Set up Java and Maven
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    # Configure Maven with settings.xml
    - name: Configure Maven for Nexus
      run: |
        mkdir -p ~/.m2
        cp settings.xml ~/.m2/settings.xml
      env:
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

    # Compile, Test, Package
    - name: Compile, Test, and Build JAR
      env:
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      run: mvn clean install --settings ~/.m2/settings.xml

    # Deploy artifact to Nexus
    - name: Deploy to Nexus
      env:
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      run: mvn deploy -DskipTests --settings ~/.m2/settings.xml

    # Docker Build
    - name: Build Docker Image
      run: |
        docker build -t maven-nexus:${{ github.sha }} .
        docker tag maven-nexus:${{ github.sha }} ${{ secrets.ECR_REPOSITORY_URI }}/maven-nexus:latest

    # Trivy Security Scan
    - name: Trivy Scan
      run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image maven-nexus:${{ github.sha }}

    # Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Login to Amazon ECR
    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}

    # Push Docker Image to ECR
    - name: Push Docker Image to ECR
      run: docker push ${{ secrets.ECR_REPOSITORY_URI }}/maven-nexus:latest

    # Configure kubeconfig for EC2 Kubernetes cluster
    - name: Configure kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG_CONTENT }}" | base64 -d > ~/.kube/config
        yq eval '.clusters[0].cluster["insecure-skip-tls-verify"] = true | del(.clusters[0].cluster.certificate-authority-data)' -i ~/.kube/config
        chmod 600 ~/.kube/config
      shell: bash

    # Deploy to EC2 Kubernetes
    - name: Deploy to Self-Hosted Kubernetes
      run: |
        kubectl version --client
        kubectl get nodes
        kubectl apply -f deployment-service.yaml
